# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/components/kyma-metrics-collector"
    labels:
      - "go"
      - "skip-review"
      - "area/dependency"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "gomod"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/components/kyma-metrics-collector"
    labels:
      - "docker"
      - "area/dependency"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "docker"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/components/kubeconfig-service"
    labels:
      - "go"
      - "skip-review"
      - "area/dependency"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "gomod"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/components/kubeconfig-service"
    labels:
      - "docker"
      - "area/dependency"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "docker"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/tools/cli"
    labels:
      - "go"
      - "skip-review"
      - "area/dependency"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "gomod"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/tools/cli"
    labels:
      - "docker"
      - "area/dependency"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "docker"
      include: "scope"
