deployment:
  replicaCount: 1
  image:
    pullPolicy: Always
  securityContext:
    runAsUser: 2000
  strategy: {} # Read more: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  nodeSelector: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
host: "kyma-env-broker"
manageSecrets: true

broker:
  port: "8080"
  # serving health probes routes on statusPort
  statusPort: "8071"
  defaultRequestRegion: "cf-eu10"
  operationTimeout: "24h"

service:
  type: ClusterIP
  port: 80

swagger:
  virtualService:
    enabled: true

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

reconciler:
  URL: "http://kcp-mothership-reconciler.kcp-system.svc.cluster.local"

provisioner:
  URL: "http://kcp-provisioner.kcp-system.svc.cluster.local:3000/graphql"

  # Defines how long should the Kyma Environment Broker checks the status of the provisioning in the Provisioner.
  # The Provisioner timeout is defined in resources/kcp/charts/provisioner/values.yaml
  timeout: "12h"
  provisioningTimeout: "6h"
  deprovisioningTimeout: "5h"

  openstack:
      floatingPoolName: "FloatingIP-external-cp-kyma"

  gardener:
    # name of the secret with kubeconfig to the gardener cluster
    secretName: "gardener"
    # name of the gardener project
    projectName: "gopher"

director:
  scope: "runtime:read runtime:write"

additionalRuntimeComponents: |-
  - name: "service-manager-proxy"
    namespace: "kyma-system"
  - name: "uaa-activator"
    namespace: "kyma-system"
  - name: "compass-runtime-agent"
    namespace: "compass-system"
  - name: "knative-eventing-kafka"
    namespace: "knative-eventing"

newAdditionalRuntimeComponents: |-
  - name: "service-manager-proxy"
    namespace: "kyma-system"
  - name: "compass-runtime-agent"
    namespace: "compass-system"

trialRegionsMapping: |-
  cf-eu10: europe
  cf-us10: us
  cf-apj21: asia

skrOIDCDefaultValues: |-
  clientID: "9bd05ed7-a930-44e6-8c79-e6defeb7dec9"
  issuerURL: "https://kymatest.accounts400.ondemand.com"
  groupsClaim: "groups"
  signingAlgs: [ "RS256" ]
  usernamePrefix: "-"
  usernameClaim: "sub"

skrDNSProvidersValues: |-
  providers: []

kymaVersion: "1.13.0"
kymaPreviewVersion: "2.0"
kymaVersionOnDemand: "false"

disableProcessOperationsInProgress: "false"
enablePlans: "azure,gcp,azure_lite,azure_ha,trial"
onlySingleTrialPerGA: "true"
enableKubeconfigURLLabel: "false"
includeAdditionalParamsInSchema: "false"

osbUpdateProcessingEnabled: "false"

gardener:
  project: "kyma-dev" # Gardener project connected to SA for HAP credentials lookup
  shootDomain: "kyma-dev.shoot.canary.k8s-hana.ondemand.com"
  kubeconfigPath: "/gardener/kubeconfig/kubeconfig"
  secretName: "gardener-credentials"
  kubernetesVersion: "1.16.9"
  defaultShootPurpose: "development"
  # if empty, the Gardener default value is used
  machineImage: ""
  # if empty, the Gardener default value is used
  machineImageVersion: ""
  trialNodesNumber: "1"
  freemiumProviders: "azure,aws"
  defaultTrialProvider: "Azure" # Azure, AWS
  autoUpdateKubernetesVersion: "true"
  autoUpdateMachineImageVersion: "false"

kubeconfig:
  issuerURL: "TBD"
  clientID: "TBD"
  allowOrigins: "*"

# It is used to provide own creds for Service Manager instead of using the one provided by external system
# who execute provision call on Kyma Environment Broker. You can define `overrideMode` to be one of: Always, WhenNotSentInRequest, Never
serviceManager:
  overrideMode: "Never" # possible values: Always, WhenNotSentInRequest, Never
  secretName: "service-manager-creds"
  url: "TBD"
  username: "TBD"
  password: "TBD"
  subaccountWithRequestCredentials: "TBD"

avs:
  secretName: "avs-creds"
  apiEndpoint: "TBD"
  apiKey: "TBD"
  clientId: "TBD"
  oauthPassword: "TBD"
  oauthTokenEndpoint: "TBD"
  oauthUserName: "TBD"
  internalTesterAccessId: "40"
  externalTesterAccessId: "40"
  groupId: "40"
  parentId: "40"
  # if set - overrides default tester service name
  internalTesterService: ""
  externalTesterService: ""
  # List of tags to bind to testers.
  # Example:
  # internalTesterTags: |-
  #   - content: tag-A
  #     tag_id: 1
  #     tag_name: value-A
  #   - content: tag-B
  #     tag_id: 2
  #     tag_name: value-B
  internalTesterTags: ""
  externalTesterTags: ""
  additionalTagsEnabled: "false"
  gardenerSeedNameTagClassId: "0"
  gardenerShootNameTagClassId: "0"
  regionTagClassId: "0"
  trialApiKey: ""
  trialInternalTesterAccessId: "0"
  trialGroupId: "0"
  trialParentId: "0"

ias:
  secretName: "ias-creds"
  url: "TBD"
  id: "TBD"
  secret: "TBD"
  identityProvider: "TBD"
  disabled: true
  tlsRenegotiationEnable: false
  skipCertVerification: false

edp:
  authURL: "TBD"
  adminURL: "TBD"
  namespace: "kyma-dev"
  environment: "dev"
  required: false
  disabled: true
  secret: "TBD"
  secretName: "edp-creds"

ems:
  disabled: true
  skipDeprovisionAzureEventingAtUpgrade: false

monitoring:
  namespace: "kcp-system"
  chartUrl: "TBD"
  remoteWriteUrl: "TBD"
  remoteWritePath: "/api/v1/write"
  disabled: true

cis:
  v1:
    authURL: "TBD"
    eventServiceURL: "TBD"
    id: "TBD"
    secret: "TBD"
    secretName: "cis-creds-v1"
  v2:
    authURL: "TBD"
    eventServiceURL: "TBD"
    id: "TBD"
    secret: "TBD"
    secretName: "cis-creds-v2"

oidc:
  issuer: https://dex.{{ .Values.global.ingress.domainName }}
  keysURL: http://dex-service.kyma-system.svc.cluster.local:5556/keys
  groups:
    admin: runtimeAdmin
    operator: runtimeOperator

kebClient:
  scope: "broker:write cld:read"

environmentsCleanup:
  schedule: "0 0 * * *"
  maxAge: "24h"
  labelSelector: "owner.do-not-delete!=true"

subaccountCleanup:
  enabled: "false"
  schedule: "0 1 * * *"

e2e:
  enabled: true
  provisioning:
    timeout: "105m"
  deprovisioning:
    timeout: "90m"
  tenant:
    id: "d9994f8f-7e46-42a8-b2c1-1bfff8d2fe05"
  aws:
    configName: "e2e-runtime-config-aws"
    planID: "361c511f-f939-4621-b228-d0fb79a1fe15"
  azure:
    configName: "e2e-runtime-config-azure"
    planID: "4deee563-e5ec-4731-b9b1-53b42d855f0c"
  free_aws:
    configName: "e2e-runtime-config-free-aws"
    planID: "b1a5764e-2ea1-4f95-94c0-2b4538b37b55"
  free_azure:
    configName: "e2e-runtime-config-free-azure"
    planID: "b1a5764e-2ea1-4f95-94c0-2b4538b37b55"
  gcp:
    configName: "e2e-runtime-config-gcp"
    planID: "ca6e5357-707f-4565-bbbd-b3ab732597c6"
  trial:
    configName: "e2e-runtime-config-suspension"
    planID: "7d55d31d-35ae-4438-bf13-6ffdfa107d9f"
  skr:
    configName: "e2e-runtime-config-skr"
    planID: "4deee563-e5ec-4731-b9b1-53b42d855f0c"
  upgrade:
    configName: "e2e-upgrade-runtime-config-azure"
    timeout: "100m"
  ha_aws:
    configName: "e2e-runtime-config-ha-aws"
    planID: "aecef2e6-49f1-4094-8433-eba0e135eb6a"  
