global:
  images:
    kyma_environment_broker:
      dir:
      version: "PR-2474"
    kyma_environments_cleanup_job:
      dir:
      version: "PR-2363"
    kyma_environments_subaccount_cleanup_job:
      dir:
      version: "PR-2337"
    kyma_environment_trial_cleanup_job:
      dir:
      version: "PR-2337"
    kyma_environment_deprovision_retrigger_job:
      dir:
      version: "PR-2482"

deployment:
  replicaCount: 1
  image:
    pullPolicy: Always
  securityContext:
    runAsUser: 2000
  strategy: {} # Read more: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  nodeSelector: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
host: "kyma-env-broker"
manageSecrets: true

broker:
  port: "8080"
  # serving health probes routes on statusPort
  statusPort: "8071"
  defaultRequestRegion: "cf-eu10"
  operationTimeout: "24h"
  profiler:
    memory: false
  events:
    enabled: false

service:
  type: ClusterIP
  port: 80

swagger:
  virtualService:
    enabled: true

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

reconciler:
  URL: "http://kcp-mothership-reconciler.kcp-system.svc.cluster.local"
  # Defines how long KEB checks the status of the provisioning reconciliation.
  provisioningTimeout: "2h"
  disabled: "false"

lifecycleManager:
  disabled: "true"

provisioner:
  URL: "http://kcp-provisioner.kcp-system.svc.cluster.local:3000/graphql"

  # Defines how long should the Kyma Environment Broker checks the status of the provisioning in the Provisioner.
  # The Provisioner timeout is defined in resources/kcp/charts/provisioner/values.yaml
  timeout: "12h"
  provisioningTimeout: "6h"
  deprovisioningTimeout: "5h"

  openstack:
      floatingPoolName: "FloatingIP-external-cp-kyma"

  gardener:
    # name of the secret with kubeconfig to the gardener cluster
    secretName: "gardener"
    # name of the gardener project
    projectName: "gopher"

director:
  scope: "runtime:read runtime:write"

additionalRuntimeComponents: |-
  - name: "service-manager-proxy"
    namespace: "kyma-system"
  - name: "uaa-activator"
    namespace: "kyma-system"
  - name: "compass-runtime-agent"
    namespace: "kyma-system"
  - name: "knative-eventing-kafka"
    namespace: "knative-eventing"

newAdditionalRuntimeComponents: |-
  - name: "service-manager-proxy"
    namespace: "kyma-system"
  - name: "compass-runtime-agent"
    namespace: "kyma-system"

trialRegionsMapping: |-
  cf-eu10: europe
  cf-us10: us
  cf-apj21: asia

skrOIDCDefaultValues: |-
  clientID: "9bd05ed7-a930-44e6-8c79-e6defeb7dec9"
  issuerURL: "https://kymatest.accounts400.ondemand.com"
  groupsClaim: "groups"
  signingAlgs: [ "RS256" ]
  usernamePrefix: "-"
  usernameClaim: "sub"

skrDNSProvidersValues: |-
  providers: []

euAccessWhitelistedGlobalAccountIds: |-
  whitelist:
euAccessRejectionMessage: "Due to limited availability, you need to open support ticket before attempting to provision Kyma clusters in EU Access only regions"

kymaVersion: "2.0"
kymaVersionOnDemand: "false"

disableProcessOperationsInProgress: "false"
enablePlans: "azure,gcp,azure_lite,trial"
onlySingleTrialPerGA: "true"
enableKubeconfigURLLabel: "false"
includeAdditionalParamsInSchema: "false"
showTrialExpirationInfo: "false"
subaccountsIdsToShowTrialExpirationInfo: "a45be5d8-eddc-4001-91cf-48cc644d571f"
trialDocsURL: "https://help.sap.com/docs/"

osbUpdateProcessingEnabled: "false"

gardener:
  project: "kyma-dev" # Gardener project connected to SA for HAP credentials lookup
  shootDomain: "kyma-dev.shoot.canary.k8s-hana.ondemand.com"
  kubeconfigPath: "/gardener/kubeconfig/kubeconfig"
  secretName: "gardener-credentials"
  kubernetesVersion: "1.16.9"
  defaultShootPurpose: "development"
  # if empty, the Gardener default value is used
  machineImage: ""
  # if empty, the Gardener default value is used
  machineImageVersion: ""
  trialNodesNumber: "1"
  freemiumProviders: "azure,aws"
  defaultTrialProvider: "Azure" # Azure, AWS
  autoUpdateKubernetesVersion: "true"
  autoUpdateMachineImageVersion: "false"
  multiZoneCluster: "false"

kubeconfig:
  issuerURL: "TBD"
  clientID: "TBD"
  allowOrigins: "*"

avs:
  secretName: "avs-creds"
  apiEndpoint: "TBD"
  apiKey: "TBD"
  clientId: "TBD"
  oauthPassword: "TBD"
  oauthTokenEndpoint: "TBD"
  oauthUserName: "TBD"
  internalTesterAccessId: "40"
  externalTesterAccessId: "40"
  groupId: "40"
  parentId: "40"
  # if set - overrides default tester service name
  internalTesterService: ""
  externalTesterService: ""
  # List of tags to bind to testers.
  # Example:
  # internalTesterTags: |-
  #   - content: tag-A
  #     tag_id: 1
  #     tag_name: value-A
  #   - content: tag-B
  #     tag_id: 2
  #     tag_name: value-B
  internalTesterTags: ""
  externalTesterTags: ""
  additionalTagsEnabled: "false"
  gardenerSeedNameTagClassId: "0"
  gardenerShootNameTagClassId: "0"
  regionTagClassId: "0"
  trialApiKey: ""
  trialInternalTesterAccessId: "0"
  trialGroupId: "0"
  trialParentId: "0"

ias:
  secretName: "ias-creds"
  url: "TBD"
  id: "TBD"
  secret: "TBD"
  identityProvider: "TBD"
  disabled: true
  tlsRenegotiationEnable: false
  skipCertVerification: false

edp:
  authURL: "TBD"
  adminURL: "TBD"
  namespace: "kyma-dev"
  environment: "dev"
  required: false
  disabled: true
  secret: "TBD"
  secretName: "edp-creds"

ems:
  disabled: true
  skipDeprovisionAzureEventingAtUpgrade: false

cis:
  v1:
    authURL: "TBD"
    eventServiceURL: "TBD"
    id: "TBD"
    secret: "TBD"
    secretName: "cis-creds-v1"
  v2:
    authURL: "TBD"
    eventServiceURL: "TBD"
    id: "TBD"
    secret: "TBD"
    secretName: "cis-creds-v2"

notification:
  url: "TBD"
  disabled: true

oidc:
  issuer: https://kymatest.accounts400.ondemand.com
  keysURL: https://kymatest.accounts400.ondemand.com/oauth2/certs
  groups:
    admin: runtimeAdmin
    operator: runtimeOperator
    orchestrations: orchestrationsAdmin

kebClient:
  scope: "broker:write cld:read"

runtimeAllowedPrincipals: |-
  - cluster.local/ns/kcp-system/sa/kcp-kyma-metrics-collector

environmentsCleanup:
  schedule: "0 0 * * *"
  maxAge: "24h"
  labelSelector: "owner.do-not-delete!=true"

subaccountCleanup:
  enabled: "false"
  schedule: "0 1 * * *"

trialCleanup:
  schedule: "0,15,30,45 * * * *"
  dryRun: true
  expirationPeriod: 336h

deprovisionRetrigger:
  schedule: "0 2 * * *"
  dryRun: true

serviceMonitor:
  scrapeTimeout: 10s
  interval: 30s

dashboardConfig:
  landscapeURL: "https://dashboard.dev.kyma.cloud.sap"
