deployment:
  image:
    pullPolicy: IfNotPresent
    path: pkosiec/kcp-runtime-director:v1
  resources: {}
  args:
    containerPort: &port 3000
  securityContext: # Set on container level
    runAsUser: 2000
    allowPrivilegeEscalation: false
  strategy: {} # Read more: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  nodeSelector: {}

service:
  port: *port
