{{- if and .Values.global.mothership_reconciler.auditlog.enabled .Values.global.mothership_reconciler.auditlog.useTestConfig }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.mothership_reconciler.auditlog.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  auditlog-user: {{ "testuser" | b64enc }}
  auditlog-password: {{ "testpassword" | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  {{- include "mothership-reconciler.labels" . | nindent 4 }}
  name: {{ .Values.global.mothership_reconciler.auditlog.configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  auditlog-url-basic: "http://dummyauditlog:8080" # backwards-compatible for KEB Audit Log
  auditlog-host: "http://logger"
  auditlog-port: "8080"
  auditlog-uri: "/audit-log/v2/"
  auditlog-tenant: "ef943440-8814-4863-9ca1-80edb623d1ce"
{{- end }}