{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
{{ include "mothership-reconciler.labels" . | indent 4 }}
  name: {{ include "mothership-reconciler.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  - port: fluentbit-metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: /api/v1/metrics/prometheus
    metricRelabelings:
      - action: keep
        regex: ^(fluentbit_.*|go_.*|process_.*)$
        sourceLabels:
          - __name__
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "mothership-reconciler.labels" . | indent 6 }}
{{- end }}
