{{ $global := . }}
{{- range $component := .Values.global.components }}
{{ $values := index $global.Values $component }}
{{ if not (hasKey $global.Subcharts $component) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kyma-project.io/component-reconciler: ""
    component: {{ $component }}
  name: {{ $component }}-reconciler
  namespace: {{ $global.Release.Namespace }}
spec:
  selector:
    matchLabels:
      kyma-project.io/component-reconciler: ""
      component: {{ $component }}
  replicas: {{ default $global.Values.deployment.replicasCount (($values).deployment).replicasCount }}
  template:
    metadata:
      labels:
        kyma-project.io/component-reconciler: ""
        component: {{ $component }}
    spec:
      serviceAccountName: component-reconcilers-{{ $component }}
      nodeSelector:
        {{- toYaml $global.Values.deployment.nodeSelector | nindent 8 }}
      containers:
      - image: "{{ $global.Values.global.images.component_reconciler }}"
        imagePullPolicy: {{ $global.Values.deployment.imagePullPolicy }}
        args:
          - reconciler
          - start
          - {{ $component }}
          - --workspace=/tmp/reconciler
          {{- if $global.Values.options.verbose }}
          - --verbose
          {{- end }}
          - --worker-count={{ default $global.Values.options.workerCount (($values).options).workerCount }}
        {{- if (($values).deployment).gitCloneToken }}
        env:
        - name: GIT_CLONE_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ $component }}-git-token
              key: token
        {{- end }}
        name: reconciler
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
        resources:
          {{- toYaml (default $global.Values.deployment.resources (($values).deployment).resources) | nindent 10 }}
        volumeMounts:
        - mountPath: /tmp
          name: workspace
      securityContext:
        runAsUser: 2000
      volumes:
      - emptyDir: {}
        name: workspace
---
{{- end }}
{{- end }}