{{ $global := . }}
{{- range $component, $entry := .Values.global.images.components }}
{{ if not (hasKey $global.Subcharts $component) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: component-reconcilers-{{ $component }}
  namespace:  {{ $global.Release.Namespace }}
  labels:
    app: component-reconcilers-{{ $component }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: component-reconcilers-{{ $component }}
  namespace:  {{ $global.Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: component-reconcilers-{{ $component }}
  namespace:  {{ $global.Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: component-reconcilers-{{ $component }}
    namespace:  {{ $global.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: component-reconcilers-{{ $component }}
---
{{- end }}
{{- end }}