{{- if .Values.global.kyma_metrics_collector.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kyma-metrics-collector.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
{{ include "kyma-metrics-collector.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
{{ include "kyma-metrics-collector.labels" . | indent 8 }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | trim | indent 8 }}
{{- end }}
    spec:
{{- include "kyma-metrics-collector.imagePullSecrets" . | indent 6 }}
      serviceAccountName: {{ template "kyma-metrics-collector.fullname" . }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - "--scrape-interval={{ .Values.config.scrapeInterval }}"
            - "--worker-pool-size={{ .Values.config.workerPoolSize }}"
            - "--log-level={{ .Values.config.logLevel }}"
            - "--listen-addr={{ .Values.config.port }}"
            - "--gardener-namespace={{ .Values.gardener.namespace }}"
            {{- if .Values.extraArgs }}
{{ toYaml .Values.extraArgs | trim | indent 12 }}
            {{- end }}
          env:
            - name: EDP_URL
              value: {{ .Values.edp.url | quote }}
            - name: EDP_NAMESPACE
              value: {{ .Values.edp.namespace | quote }}
            - name: EDP_TIMEOUT
              value: {{ .Values.edp.timeout | quote }}
            - name: EDP_RETRY
              value: {{ .Values.edp.retry | quote }}
            - name: EDP_DATASTREAM_NAME
              value: {{ .Values.edp.datastream.name | quote }}
            - name: EDP_DATASTREAM_VERSION
              value: {{ .Values.edp.datastream.version | quote }}
            - name: EDP_DATASTREAM_ENV
              value: {{ .Values.edp.datastream.env | quote }}
            - name: KEB_URL
              value: {{tpl .Values.keb.url .}}
            - name: KEB_TIMEOUT
              value: {{ .Values.keb.timeout | quote }}
            - name: KEB_RETRY_COUNT
              value: {{ .Values.keb.retryCount | quote }}
            - name: KEB_POLL_WAIT_DURATION
              value: {{ .Values.keb.pollWaitDuration | quote }}
            - name: PUBLIC_CLOUD_SPECS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kyma-metrics-collector.publicCloud.configMap.name" . }}
                  key: {{ .Values.publicCloudInfo.configMap.key }}
            {{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | trim | indent 12 }}
            {{- end }}
          image: {{ template "kyma-metrics-collector.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
          ports:
            - name: {{ .Values.config.portName }}
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
{{ toYaml . | trim | indent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
{{ toYaml . | trim | indent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /gardener
              name: gardener-kubeconfig
              readOnly: true
            - mountPath: /edp-credentials
              name: edp
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
      - name: gardener-kubeconfig
        secret:
          secretName: {{ .Values.gardener.secretName }}
      - name: edp
        secret:
          secretName: {{ template "kyma-metrics-collector.fullname" . }}
      - name: tmp
        emptyDir: {}
{{- end -}}