apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kyma-env-broker.fullname" . }}
  labels:
{{ include "kyma-env-broker.labels" . | indent 4 }}
data:
  additionalRuntimeComponents.yaml: |-
    components:
{{- with .Values.additionalRuntimeComponents }}
{{ tpl . $ | indent 6 }}
{{- end }}
  newAdditionalRuntimeComponents.yaml: |-
    components:
{{- with .Values.newAdditionalRuntimeComponents }}
{{ tpl . $ | indent 6 }}
{{- end }}
  trialRegionMapping.yaml: |-
{{- with .Values.trialRegionsMapping }}
{{ tpl . $ | indent 4 }}
{{- end }}
  skrOIDCDefaultValues.yaml: |-
{{- with .Values.skrOIDCDefaultValues }}
{{ tpl . $ | indent 4 }}
{{- end }}
  skrDNSCustomValues.yaml: |-
{{- with .Values.skrDNSCustomValues }}
{{ tpl . $ | indent 4 }}
{{- end }}
  catalog.yaml: |-
{{ .Files.Get "files/catalog.yaml" | indent 4 }}
