apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kyma-env-broker.fullname" . }}
  labels:
{{ include "kyma-env-broker.labels" . | indent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
data:
  additionalRuntimeComponents.yaml: |-
    components:
{{- with .Values.additionalRuntimeComponents }}
{{ tpl . $ | indent 6 }}
{{- end }}
  newAdditionalRuntimeComponents.yaml: |-
    components:
{{- with .Values.newAdditionalRuntimeComponents }}
{{ tpl . $ | indent 6 }}
{{- end }}
  trialRegionMapping.yaml: |-
{{- with .Values.trialRegionsMapping }}
{{ tpl . $ | indent 4 }}
{{- end }}
  euAccessWhitelistedGlobalAccountIds.yaml: |-
{{- with .Values.euAccessWhitelistedGlobalAccountIds }}
{{ tpl . $ | indent 4 }}
{{- end }}
  skrOIDCDefaultValues.yaml: |-
{{- with .Values.skrOIDCDefaultValues }}
{{ tpl . $ | indent 4 }}
{{- end }}
  skrDNSProvidersValues.yaml: |-
{{- with .Values.skrDNSProvidersValues }}
{{ tpl . $ | indent 4 }}
{{- end }}
  avsMaintenanceModeDuringUpgradeAlwaysDisabledGlobalAccountIDs.yaml: |-
    maintenanceModeDuringUpgradeAlwaysDisabledGAIDs:
{{- range .Values.avs.maintenanceModeDuringUpgrade.alwaysDisabledGlobalAccountIDs }}
{{ tpl . $ | print "- " | indent 6 }}
{{- end }}
  catalog.yaml: |-
{{ .Files.Get "files/catalog.yaml" | indent 4 }}
