apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kyma-env-broker.fullname" . }}
  labels:
{{ include "kyma-env-broker.labels" . | indent 4 }}
data:
  additionalRuntimeComponents.yaml: |-
    components:
{{- with .Values.additionalRuntimeComponents }}
{{ tpl . $ | indent 6 }}
{{- end }}
  trialRegionMapping.yaml: |-
{{- with .Values.trialRegionsMapping }}
{{ tpl . $ | indent 4 }}
{{- end }}
  catalog.yaml: |-
{{ .Files.Get "files/catalog.yaml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.switcher.configMapName }}"
  namespace: "{{ .Values.switcher.configMapNamespace }}"
  labels:
{{ include "kyma-env-broker.labels" . | indent 4 }}
