apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: keb-runtimes-info
spec:
  match:
    methods: ["GET"]
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></info/runtimes>
  authenticators:
  - handler: oauth2_introspection
    config:
      required_scope: ["cld:read"]
  authorizer:
    handler: allow
  upstream:
    url: http://{{ include "kyma-env-broker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: keb-api
spec:
  match:
    methods: ["GET", "PUT", "DELETE"]
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></oauth/([^/]+/)?v2/.*>
  authenticators:
  - handler: oauth2_introspection
    config:
      required_scope: ["broker:write"]
  authorizer:
    handler: allow
  upstream:
    url: http://{{ include "kyma-env-broker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: keb-upgrade
spec:
  match:
    methods: ["POST"]
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></upgrade/.*>
  authenticators:
  - handler: oauth2_introspection
    config:
      required_scope: ["broker-upgrade:write"]
  authorizer:
    handler: allow
  upstream:
    url: http://{{ include "kyma-env-broker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: keb-orchestrations
spec:
  match:
    methods: ["GET"]
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></orchestrations.*>
  authenticators:
  - handler: oauth2_introspection
    config:
      required_scope: ["broker-upgrade:read"]
  authorizer:
    handler: allow
  upstream:
    url: http://{{ include "kyma-env-broker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: keb-list-runtimes
spec:
  match:
    methods: ["GET"]
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></runtimes>
  authenticators:
    - handler: oauth2_introspection
      config:
        required_scope: ["runtimes:read"]
  authorizer:
    handler: allow
  upstream:
    url: http://{{ include "kyma-env-broker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
