apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: keb-runtimes-info
spec:
  match:
    methods: ["GET"]
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></info/runtimes>
  authenticators:
  - handler: oauth2_introspection
    config:
      required_scope: ["cld:read"]
  authorizer:
    handler: allow
  upstream:
    url: http://{{ include "kyma-env-broker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: keb-api
spec:
  match:
    methods: ["GET", "PUT", "DELETE", "PATCH"]
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></oauth/([^/]+/)?v2/.*>
  authenticators:
  - handler: oauth2_introspection
    config:
      required_scope: ["broker:write"]
  authorizer:
    handler: allow
  upstream:
    url: http://{{ include "kyma-env-broker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: keb-runtimes
  namespace: {{ .Release.Namespace }}
spec:
  authenticators:
  - handler: jwt
    config:
      jwks_urls: ["{{ tpl .Values.oidc.keysURL $ }}"]
      scope_strategy: exact
      required_scope: ["{{ .Values.oidc.groups.operator }}"]
      trusted_issuers: ["{{ tpl .Values.oidc.issuer $ }}"]
  authorizer:
    handler: allow
  match:
    methods:
    - GET
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></runtimes.*>
  upstream:
    url: http://{{ include "kyma-env-broker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: keb-orchestrations
  namespace: {{ .Release.Namespace }}
spec:
  authenticators:
  - handler: jwt
    config:
      jwks_urls: ["{{ tpl .Values.oidc.keysURL $ }}"]
      scope_strategy: exact
      required_scope: ["{{ .Values.oidc.groups.orchestrations }}"]
      trusted_issuers: ["{{ tpl .Values.oidc.issuer $ }}"]
  authorizer:
    handler: allow
  match:
    methods:
    - GET
    - PUT
    - POST
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></orchestrations.*>
  upstream:
    url: http://{{ include "kyma-env-broker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: keb-upgrade
  namespace: {{ .Release.Namespace }}
spec:
  authenticators:
  - handler: jwt
    config:
      jwks_urls: ["{{ tpl .Values.oidc.keysURL $ }}"]
      scope_strategy: exact
      required_scope: ["{{ .Values.oidc.groups.orchestrations }}"]
      trusted_issuers: ["{{ tpl .Values.oidc.issuer $ }}"]
  authorizer:
    handler: allow
  match:
    methods:
    - POST
    url: <http|https>://{{ .Values.host }}.{{ .Values.global.ingress.domainName }}<(:(80|443))?></upgrade/.*>
  upstream:
    url: http://{{ include "kyma-env-broker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:80
