apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kyma-env-broker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["list", "get"]
  - apiGroups: ["*"]
    resources: ["configmaps"]
    verbs: ["list", "get"]
  - apiGroups: ["core.gardener.cloud"]
    resources: ["shoots"]
    verbs: ["list", "get"]
  - apiGroups: ["core.gardener.cloud"]
    resources: ["secretbindings"]
    verbs: ["list", "get", "update"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kyma-env-broker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.kyma_environment_broker.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "kyma-env-broker.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.kyma_environment_broker.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
