apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}
spec:
  gateways:
  - {{ .Values.global.istio.gateway.namespace }}/{{ .Values.global.istio.gateway.name }}
  hosts:
  - {{ .Values.host }}.{{ .Values.global.ingress.domainName }}
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - X-Broker-API-Version
      allowMethods: ["GET", "PUT", "DELETE"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
        regex: /oauth/([^/]+/)?v2/.*
    route:
    - destination:
        host: {{ include "kyma-env-broker.fullname" . }}
        port:
          number: 80
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["GET"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
        regex: /info/runtimes
    route:
    - destination:
        host: {{ include "kyma-env-broker.fullname" . }}
        port:
          number: 80
  - corsPolicy:
      allowHeaders:
        - Authorization
        - Content-Type
      allowMethods: ["GET"]
      allowOrigins:
      - regex: ".*"
    match:
      - uri:
          regex: /runtimes
    route:
      - destination:
          host: {{ include "kyma-env-broker.fullname" . }}
          port:
            number: 80
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["GET", "PUT"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
        regex: /orchestrations.*
    route:
    - destination:
        host: {{ include "kyma-env-broker.fullname" . }}
        port:
          number: 80
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["POST"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
        regex: /upgrade/.*
    route:
    - destination:
        host: {{ include "kyma-env-broker.fullname" . }}
        port:
          number: 80
  - corsPolicy:
      allowHeaders:
        - Authorization
        - Content-Type
      allowMethods: ["GET"]
      allowOrigins:
      - regex: ".*"
    match:
      - uri:
          regex: /kubeconfig/.*
    route:
      - destination:
          host: kcp-kyma-environment-broker
          port:
            number: 80
  {{- if .Values.swagger.virtualService.enabled }}
  # swagger exposed without authorization on root endpoint also needs access to static resources placed under /swagger folder
  - corsPolicy:
      allowHeaders:
        - Authorization
        - Content-Type
      allowMethods: ["GET"]
      allowOrigins:
      - regex: ".*"
    match:
      - uri:
          exact: /
    route:
      - destination:
          host: {{ include "kyma-env-broker.fullname" . }}
          port:
            number: 80
  - corsPolicy:
      allowHeaders:
        - Authorization
        - Content-Type
      allowMethods: ["GET"]
      allowOrigins:
      - regex: ".*"
    match:
      - uri:
          regex: /swagger.*
    route:
      - destination:
          host: {{ include "kyma-env-broker.fullname" . }}
          port:
            number: 80
  - corsPolicy:
      allowHeaders:
        - Authorization
        - Content-Type
      allowMethods: ["GET"]
      allowOrigins:
      - regex: ".*"
    match:
      - uri:
          regex: /schema.*
    route:
      - destination:
          host: {{ include "kyma-env-broker.fullname" . }}
          port:
            number: 80
  {{- end }}
