apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}
spec:
  gateways:
  - {{ .Values.global.istio.gateway.name }}.{{ .Values.global.istio.gateway.namespace }}.svc.cluster.local
  hosts:
  - {{ .Values.host }}.{{ .Values.global.ingress.domainName }}
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - X-Broker-API-Version
      allowMethods: ["GET", "PUT", "DELETE"]
      allowOrigin: ["*"]
    match:
    - uri:
        regex: /oauth/([^/]+/)?v2/.*
    route:
    - destination:
        host: {{ .Values.global.oathkeeper.host }}
        port:
          number: {{ .Values.global.oathkeeper.port }}
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["GET"]
      allowOrigin: ["*"]
    match:
    - uri:
        regex: /info/runtimes
    route:
    - destination:
        host: {{ .Values.global.oathkeeper.host }}
        port:
          number: {{ .Values.global.oathkeeper.port }}
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["POST"]
      allowOrigin: ["*"]
    match:
    - uri:
        regex: /upgrade/.*
    route:
    - destination:
        host: {{ include "kyma-env-broker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      allowMethods: ["GET", "PUT"]
      allowOrigin: ["*"]
    match:
    - uri:
        regex: /orchestrations.*
    route:
    - destination:
        host: {{ include "kyma-env-broker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
  - corsPolicy:
      allowHeaders:
        - Authorization
        - Content-Type
      allowMethods: ["GET"]
      allowOrigin: ["*"]
    match:
      - uri:
          regex: /runtimes
    route:
      - destination:
          host: {{ include "kyma-env-broker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: {{ .Values.service.port }}
  {{- if .Values.swagger.virtualService.enabled }}
  # swagger exposed without authorization on root endpoint also needs access to static resources placed under /swagger folder
  - corsPolicy:
      allowHeaders:
        - Authorization
        - Content-Type
      allowMethods: ["GET"]
      allowOrigin: ["*"]
    match:
      - uri:
          exact: /
    route:
      - destination:
          host: {{ include "kyma-env-broker.fullname" . }}
          port:
            number: 80
  - corsPolicy:
      allowHeaders:
        - Authorization
        - Content-Type
      allowMethods: ["GET"]
      allowOrigin: ["*"]
    match:
      - uri:
          regex: /swagger.*
    route:
      - destination:
          host: {{ include "kyma-env-broker.fullname" . }}
          port:
            number: 80
  - corsPolicy:
      allowHeaders:
        - Authorization
        - Content-Type
      allowMethods: ["GET"]
      allowOrigin: ["*"]
    match:
      - uri:
          regex: /schema.*
    route:
      - destination:
          host: {{ include "kyma-env-broker.fullname" . }}
          port:
            number: 80
  {{ end }}
