nameOverride: ""
fullnameOverride: ""

image:
  # these override the values from global chart
  repository: ""
  tag: ""
  pullSecrets: []
  pullPolicy: IfNotPresent

resources: {}
  # requests:
  #   memory: "64Mi"
  #   cpu: "50m"
  # limits:
  #   memory: "250Mi"
  #   cpu: "200m"

nodeSelector: {}

securityContext:
  runAsUser: 1001

podAnnotations:
  sidecar.istio.io/inject: "false"

loglevel: info
port: 8080
serviceAccount:
  enabled: true
  ## Name of an already existing service account. Setting this value disables the automatic service account creation.
  # name:

gardener:
  secretName: "gardener-credentials"

provider:
  pollinterval: "1m"
  workers: 5
  buffer: 100

edp:
  datastream:
    name: "TBD"
    namespace: "TBD"
    version: 1
    env: "TBD"
  token: "TBD"
  url: "TBD"
  workers: 5
  buffer: 100
  timeout: "30s"
  retry: 5

metrics:
  enabled: false
  service:
    type: ClusterIP
    annotations: {}
    loadBalancerIP:
  serviceMonitor:
    enabled: false
     # labels configured in prometheus-operator for the prometheus serviceMonitorSelector
    additionalLabels: {}
    # namespace configured in prometheus-operator for the prometheus serviceMonitorSelector
    # namespace: kyma-system
    # interval: 30s
    # scrapeTimeout: 10s
  prometheusRule:
    enabled: false
     # labels configured in prometheus-operator for the prometheus ruleSelector
    additionalLabels:
      app: monitoring
      release: monitoring
    # namespace configured in prometheus-operator for the prometheus ruleSelector
    # namespace: kyma-system
    rules: |-
    ## This is just an example, please adapt it to your needs.
    # metris-group-rules-1:
    #   - alert: MetrisDown
    #     expr: |-
    #       up{job="kcp-metris",namespace="kcp-system"} == 0
    #     for: 5m
    #     labels:
    #       severity: critical
    #     annotations:
    #       message: |-
    #         Metris has disappeared from Prometheus target discovery.

  grafanaDashboard:
    enabled: false
    # labels configured in prometheus-operator for the grafana dashboards sidecar
    additionalLabels:
      grafana_dashboard: "1"
    # namespace configured in prometheus-operator for the grafana dashboards sidecar
    # namespace: kyma-system

# Define custom environment variables to pass to metris
  # â€” name: ENV_VAR1
  #   value: test1
  # - name: ENV_VAR2
  #   valueFrom:
  #     secretKeyRef:
  #       name: secretname
  #       key: secretkey
extraEnv: []

# Define custom arguments to pass to metris container
extraArgs: []